import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { CTA, Eyebrow } from "@/components/sections";
import { services } from "@/data/services";
import { metadata as createMetadata } from "@/lib/seo";
import { FAQSection } from "@/components/faq";
import { servicesPageFaqs } from "@/data/faqs";
export const metadata=createMetadata("Heating, Cooling & HVAC Services","Explore HVAC repair, installation, maintenance, water heater, duct cleaning, and commercial service across Northern Virginia and Washington, DC.","/services");
export default function Services(){return <><section className="page-hero"><div className="container"><div className="breadcrumbs"><Link href="/">Home</Link> / Services</div><Eyebrow>Heating • Cooling • Property support</Eyebrow><h1>Complete HVAC services for homes, businesses, and apartments.</h1><p>Professional repairs, installations, and preventative care delivered with responsive communication across Northern Virginia, Maryland, and Washington, DC.</p></div></section><section className="section"><div className="container"><div className="section-head"><div><Eyebrow>Our services</Eyebrow><h2>Solutions for every season and property type.</h2></div></div><div className="card-grid">{services.map(s=><Link className="service-card" href={`/services/${s.slug}`} key={s.slug}><p className="eyebrow">{s.eyebrow}</p><h3>{s.title}</h3><p>{s.short}</p><span className="text-link">View service <ArrowRight size={16}/></span></Link>)}</div></div></section><section className="section section-soft"><div className="container"><div className="section-head"><div><Eyebrow>A straightforward process</Eyebrow><h2>Clear from the first call to the final check.</h2></div></div><div className="why-grid">{[["01","Request service","Call or send the details online."],["02","Evaluate","We inspect the system and identify the issue."],["03","Recommend","You receive a clear explanation and practical options."],["04","Complete","We perform the work and verify operation."]].map(([n,t,d])=><div className="why-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section><FAQSection items={servicesPageFaqs} title="Questions about our HVAC services"/><CTA/></>}
