import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Phone, Snowflake, Thermometer, Wrench, Wind } from "lucide-react";
import { CTA, Eyebrow, TrustRow } from "@/components/sections";
import { blogs } from "@/data/blogs";
import { projects } from "@/data/projects";
import { services } from "@/data/services";
import { images, site } from "@/data/site";
import { metadata as createMetadata } from "@/lib/seo";
import { FAQSection } from "@/components/faq";
import { homeFaqs } from "@/data/faqs";
export const metadata = createMetadata("HVAC Services in Northern Virginia & Washington, DC", "Reliable heating, cooling, water heater, duct cleaning, and commercial HVAC service for homes and properties across Northern Virginia and Washington, DC.", "/");
const icons = [Snowflake,Thermometer,Wrench,Wind];
export default function Home(){return <>
  <section className="hero"><Image className="hero-bg" src={images.hero} alt="Hot & Cool Services technician arriving for HVAC service" fill priority sizes="100vw"/><div className="container hero-content"><Eyebrow>HVAC service across VA • MD • DC</Eyebrow><h1>Reliable HVAC Services for Homes, Apartments & <span>Commercial Properties</span></h1><p className="hero-copy">Professional heating, cooling, water heater, duct cleaning, and HVAC maintenance services across Northern Virginia, Washington, DC, and surrounding areas.</p><div className="hero-actions"><Link className="btn btn-red" href="/contact">Request Service <ArrowRight size={18}/></Link><a className="btn btn-outline hero-phone" href={site.phoneHref}><Phone size={18}/> {site.phone}</a></div><div className="hero-trust"><span><Check size={17}/> Homes & businesses</span><span><Check size={17}/> Apartments & managed properties</span><span><Check size={17}/> Repairs, installs & maintenance</span></div></div></section>
  <div className="container trust-shell"><TrustRow/></div>
  <section className="section"><div className="container"><div className="section-head"><div><Eyebrow>Complete comfort services</Eyebrow><h2>One dependable team for the systems your property relies on.</h2><p>From an urgent repair to planned replacement and preventative care, our service is built around clear communication and quality work.</p></div><Link className="text-link" href="/services">Explore all services <ArrowRight size={18}/></Link></div><div className="card-grid">{services.map((s,i)=>{const Icon=icons[i%icons.length];return <Link className="service-card" href={`/services/${s.slug}`} key={s.slug}><span className="service-icon"><Icon/></span><h3>{s.title}</h3><p>{s.short}</p><span className="text-link">View service <ArrowRight size={16}/></span></Link>})}</div></div></section>
  <section className="section field-story">
    <div className="container field-story-grid">
      <div className="field-story-visual">
        <div className="field-photo field-photo-main"><Image src={images.soldering} alt="Hot & Cool Services technician soldering an HVAC system connection" fill sizes="(max-width: 900px) 92vw, 46vw"/></div>
        <div className="field-photo field-photo-secondary"><Image src={images.worker} alt="Hot & Cool Services technician servicing indoor HVAC equipment" fill sizes="(max-width: 620px) 44vw, 20vw"/></div>
        <div className="field-photo-label"><strong>Real work in progress</strong><span>Skilled service inside the properties we support.</span></div>
      </div>
      <div className="field-story-copy">
        <Eyebrow>People behind the service</Eyebrow>
        <h2>Hands-on HVAC work, handled with care.</h2>
        <p>Good service is more than arriving with the right tools. Our technicians take time to understand the system, protect the surrounding space, and complete each approved repair with attention to the details.</p>
        <ul className="check-list">
          <li><Check/>Careful diagnosis before recommendations</li>
          <li><Check/>Respectful work inside occupied homes and properties</li>
          <li><Check/>Clear updates from arrival through completion</li>
        </ul>
        <Link className="btn btn-red" href="/about">Meet Hot & Cool Services <ArrowRight size={18}/></Link>
      </div>
    </div>
  </section>
  <section className="section section-soft"><div className="container split"><div><Eyebrow>Commercial & multifamily</Eyebrow><h2>HVAC support that works with your property operations.</h2><p>We help property managers, general contractors, apartment communities, and businesses resolve comfort issues, coordinate access, and plan equipment work with less disruption.</p><ul className="check-list"><li><Check/>Responsive repair and tenant-comfort service</li><li><Check/>Apartment and multi-unit coordination</li><li><Check/>Commercial installation and replacement</li><li><Check/>Ongoing preventative maintenance</li></ul><Link className="btn btn-red" href="/services/commercial-hvac">Commercial HVAC <ArrowRight size={18}/></Link><div className="stats"><div className="stat"><strong>VA • MD • DC</strong><span>Regional coverage</span></div><div className="stat"><strong>Homes + properties</strong><span>Flexible service</span></div><div className="stat"><strong>Clear updates</strong><span>From start to finish</span></div></div></div><div className="image-card"><Image src={images.commercial} alt="Commercial HVAC equipment service" fill sizes="(max-width: 900px) 100vw, 48vw"/><div className="image-badge"><strong>Commercial ready</strong><span>Service built for apartments, offices, and managed properties.</span></div></div></div></section>
  <section className="urgent-strip"><div className="container urgent-inner"><div><span>Fast-response service</span><h2>Urgent heating or cooling problem?</h2><p>Call directly so our team can understand the issue and identify the fastest available next step.</p></div><a className="btn btn-light" href={site.phoneHref}><Phone size={18}/> Call {site.phone}</a></div></section>
  <section className="section section-dark"><div className="container"><div className="section-head"><div><Eyebrow>Featured work</Eyebrow><h2>Property projects built on trust and follow-through.</h2><p>Real multifamily and commercial experience across Maryland, Washington, DC, and Northern Virginia.</p></div><Link className="text-link" href="/projects">View projects <ArrowRight size={18}/></Link></div><div className="project-grid">{projects.map(p=><article className="project-card" key={p.name}><div className="project-img"><Image src={p.images[0]} alt={`${p.name} HVAC project`} width={900} height={650}/></div><div className="project-copy"><span className="project-meta">{p.location} • {p.type}</span><h3>{p.name}</h3><p>{p.description}</p></div></article>)}</div></div></section>
  <section className="section"><div className="container"><div className="section-head"><div><Eyebrow>Why Hot & Cool</Eyebrow><h2>Professional service without the runaround.</h2></div></div><div className="why-grid">{[["01","Fast response","Prompt scheduling and direct communication when comfort cannot wait."],["02","Property experience","Capable support for homeowners, offices, apartments, and managed communities."],["03","Honest guidance","Clear explanations and practical options before work begins."],["04","Clean workmanship","Organized, respectful service with attention to the details."]].map(([n,t,d])=><div className="why-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
  <section className="section section-soft"><div className="container"><div className="section-head"><div><Eyebrow>Customer confidence</Eyebrow><h2>Trusted across homes, businesses, and managed properties.</h2><p>Responsive communication and professional work are the foundation of every service relationship.</p></div></div><div className="testimonial-grid"><figure><div className="stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“Hot & Cool Services has been dependable, responsive, and professional whenever our property needs HVAC work.”</blockquote><figcaption>Property management team<br/><span>Washington, DC</span></figcaption></figure><figure><div className="stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“They diagnosed the issue quickly, explained the repair clearly, and completed the work without any hassle.”</blockquote><figcaption>Residential customer<br/><span>Northern Virginia</span></figcaption></figure><figure><div className="stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“Professional, clean, and easy to work with. They handled service for multiple units smoothly.”</blockquote><figcaption>Apartment community client<br/><span>Washington, DC</span></figcaption></figure></div></div></section>
  <CTA dark title="Heating or cooling problem? Let’s get it handled." text="Call for the fastest response or send a service request and our team will follow up."/>
  <section className="section section-soft"><div className="container"><div className="section-head"><div><Eyebrow>Comfort notes</Eyebrow><h2>Practical HVAC advice for local homeowners.</h2></div><Link className="text-link" href="/blog">Visit the blog <ArrowRight size={18}/></Link></div><div className="blog-grid">{blogs.map(p=><article className="blog-card" key={p.slug}><time>{new Date(`${p.date}T12:00:00`).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})} • {p.readTime}</time><h3>{p.title}</h3><p>{p.description}</p><Link className="text-link" href={`/blog/${p.slug}`}>Read article <ArrowRight size={16}/></Link></article>)}</div></div></section>
  <FAQSection items={homeFaqs} title="HVAC service questions, answered." intro="What homeowners, businesses, and property teams commonly ask before scheduling service."/>
  <CTA/>
</>}
